
const list = [
    {   
        productName:'skirt',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for girls',
        date:'',
        img: './images/long skirt1.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'skirt',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for women',
        date:'',
        img: './images/long skirt2.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'skirt',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for girls',
        date:'',
        img: './images/long skirt3.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'short',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for girls',
        date:'',
        img: './images/short1.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'short',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for gitls',
        date:'',
        img: './images/short2.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'short',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for girls',
        date:'',
        img: './images/short3.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'short',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for boys',
        date:'',
        img: './images/short4.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'skirt',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for girls',
        date:'',
        img: './images/shortskirt1.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'skirt',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for girls',
        date:'',
        img: './images/shortskirt2.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'skirt',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for girls',
        date:'',
        img: './images/shortskirt3.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'jumpsuit',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for girls',
        date:'',
        img: './images/jumpsuit.jpeg',
        description:'',
        status:'in stock',
    },
    {   
        productName:'dress',
        storeName:'KigaliStore_cloth',
        price:'$35',
        category:'for gitls',
        date:'',
        img: './images/dress3.jpeg',
        description:'',
        status:'in stock',
    }, 
]
export default list
